--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/theSpawn
build-by-default: true
branches:
- master
- development
projects:
  theSpawn:
    icon: "icon.png"
    path: ""
    php: 8.1
    libs:
      - src: "https://https://jaxkdev.loca.lt/ci/PoggitTestPlugins/EasyUI/libEasyUI"
        branch: "pm5"